version: '3.7'

services:
  app:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./app/app/.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    ports:
      - 5433:5432
    volumes:
      - example_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=example_db

volumes:
  example_volume: